version: '3.7'
services:
  backend:
    build:
      context: .
    env_file:
      - .docker-env.development
    depends_on:
      - db
    ports:
      - 4001:4001
  db:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
volumes:
  db-data:
